#!/bin/bash
# @project: Automatic Git syncing
# @author: Koen van der Kruk (koen-github), swiftgame
# @version: 1.0
# @repository: https://github.com/swiftgame/auto_sync_git_repos
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

FULL_PATH=`pwd`
SSHFS_SERVERS=""
MOUNT_POINTS=""
ANOTHER_ONE="y"


function ask_for_input(){
	echo "Enter remote SSHFS location: "
	read SSHFS_SERVER

	echo "Enter mountpoint where the SSHFS location is mounted on: "
	read MOUNT_POINT

	SSHFS_SERVERS+="$SSHFS_SERVER,"
	MOUNT_POINTS+="$MOUNT_POINT,"

	echo "Do you want to add another remote location? (y/n)"
	read ANOTHER_ONE

	if [[ $ANOTHER_ONE == "y" ]]
	then
		ask_for_input
	fi

	#return $ANOTHER_ONE

}

if [[ $ANOTHER_ONE == "y" ]]
then
	ask_for_input
fi


echo $SSHFS_SERVERS
echo $MOUNT_POINTS

echo "Specify the automatic git commit message:"
read GIT_COMMIT_TEXT

echo "Specify full location to save this config file: "
read CONFIG_FILE_LOCATION


echo "declare CLONE_DIRS=(" > $CONFIG_FILE_LOCATION
mountpoints=$(echo $MOUNT_POINTS | tr "," "\n")

for x in $mountpoints
do
	echo "\"$x\" " >> $CONFIG_FILE_LOCATION
done

echo ")" >> $CONFIG_FILE_LOCATION
echo "declare EXT_SERVERS=(" >> $CONFIG_FILE_LOCATION

sshfsservers=$(echo $SSHFS_SERVERS | tr "," "\n")
arrIN=(${MOUNT_POINTS//,/ })
iterator="0"

for x in $sshfsservers
do
	echo "\"$x\" \""${arrIN[$iterator]}"\"" >> $CONFIG_FILE_LOCATION
	((iterator+=1))
done

echo ")" >> $CONFIG_FILE_LOCATION
chmod 644 $CONFIG_FILE_LOCATION

echo "Run git sync script with this command:
./git-syncing $CONFIG_FILE_LOCATION $GIT_COMMIT_TEXT YES

"
